image:
  repository: 0000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/spring-kubernetes-example
  pullPolicy: Always
  tag: "1"

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:1111111111111:certificate/1234-5678-0000
  hosts:
    - host: qa-k8s.spring.io
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
   limits:
     cpu: 1024m
     memory: 1024Mi
   requests:
     cpu: 1024m
     memory: 1024Mi

env: "qa"

javaOptions:
  - -XX:+UseContainerSupport
